// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbeOgvK43rexOTRZauhAyFHqhC3ocvlAs',
    appId: '1:647128757707:web:86828ce04b70b6d8ef724e',
    messagingSenderId: '647128757707',
    projectId: 'pokedex-c45b6',
    authDomain: 'pokedex-c45b6.firebaseapp.com',
    storageBucket: 'pokedex-c45b6.appspot.com',
    measurementId: 'G-E4NCWQM28J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GsUAa5L_7hvawPvbw2rNbRt3Epbftso',
    appId: '1:647128757707:android:6a86ec49e9304ceeef724e',
    messagingSenderId: '647128757707',
    projectId: 'pokedex-c45b6',
    storageBucket: 'pokedex-c45b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA93rg0nXe4AHt2ge0DB82EtPATwTdhYz0',
    appId: '1:647128757707:ios:540bc16fc3014e1eef724e',
    messagingSenderId: '647128757707',
    projectId: 'pokedex-c45b6',
    storageBucket: 'pokedex-c45b6.appspot.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA93rg0nXe4AHt2ge0DB82EtPATwTdhYz0',
    appId: '1:647128757707:ios:32b1798a75d14fd1ef724e',
    messagingSenderId: '647128757707',
    projectId: 'pokedex-c45b6',
    storageBucket: 'pokedex-c45b6.appspot.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
